# Generated by Django 4.2.2 on 2023-06-15 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assessment_name",
                    models.CharField(max_length=255, verbose_name="Название оценки"),
                ),
            ],
            options={
                "verbose_name": "Оценивающий тест",
                "verbose_name_plural": "Оценивающие тесты",
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "short_description",
                    models.CharField(max_length=255, verbose_name="Краткое описание"),
                ),
                (
                    "what_you_will_learn",
                    models.CharField(
                        max_length=255, verbose_name="Навыки, получаемые в курсе"
                    ),
                ),
                (
                    "teaser_video_link",
                    models.CharField(
                        max_length=255, verbose_name="Ссылка на видео-анонс курса"
                    ),
                ),
                (
                    "course_icon",
                    models.CharField(
                        max_length=255, verbose_name="Путь к иконке курса"
                    ),
                ),
            ],
            options={
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(max_length=255, verbose_name="Имя пользователя"),
                ),
                ("password", models.CharField(max_length=255, verbose_name="Пароль")),
            ],
            options={
                "verbose_name": "Студент",
                "verbose_name_plural": "Студенты",
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "short_description",
                    models.CharField(max_length=255, verbose_name="Краткое описание"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="first.course",
                        verbose_name="Курс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тема",
                "verbose_name_plural": "Темы",
            },
        ),
        migrations.CreateModel(
            name="Subtopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "short_description",
                    models.CharField(max_length=255, verbose_name="Краткое описание"),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="first.topic",
                        verbose_name="Тема",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подтема",
                "verbose_name_plural": "Подтемы",
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255, verbose_name="Вопрос")),
                (
                    "correct_option",
                    models.CharField(max_length=255, verbose_name="Правильный вариант"),
                ),
                (
                    "option_a",
                    models.CharField(max_length=255, verbose_name="Вариант A"),
                ),
                (
                    "option_b",
                    models.CharField(max_length=255, verbose_name="Вариант B"),
                ),
                (
                    "option_c",
                    models.CharField(max_length=255, verbose_name="Вариант C"),
                ),
                (
                    "option_d",
                    models.CharField(max_length=255, verbose_name="Вариант D"),
                ),
                (
                    "option_e",
                    models.CharField(max_length=255, verbose_name="Вариант E"),
                ),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="first.assessment",
                        verbose_name="Оценка",
                    ),
                ),
                (
                    "subtopic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="first.subtopic",
                        verbose_name="Подтема",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="first.topic",
                        verbose_name="Тема",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вопрос",
                "verbose_name_plural": "Вопросы",
            },
        ),
        migrations.CreateModel(
            name="Progress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "selected_option",
                    models.CharField(max_length=255, verbose_name="Выбранный вариант"),
                ),
                ("score", models.IntegerField(verbose_name="Оценка")),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="first.question",
                        verbose_name="Вопрос",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="first.student",
                        verbose_name="Студент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Прогресс",
                "verbose_name_plural": "Прогресс",
            },
        ),
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_path",
                    models.CharField(max_length=255, verbose_name="Путь к файлу"),
                ),
                (
                    "subtopic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="first.subtopic",
                        verbose_name="Подтема",
                    ),
                ),
            ],
            options={
                "verbose_name": "Контент",
                "verbose_name_plural": "Контент",
            },
        ),
        migrations.AddField(
            model_name="assessment",
            name="content",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="first.content",
                verbose_name="Контент",
            ),
        ),
    ]
