# Generated by Django 4.2.2 on 2023-06-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("first", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="teaser_video_link",
            field=models.URLField(
                max_length=255, verbose_name="Ссылка на видео-анонс курса"
            ),
        ),
    ]
