# Generated by Django 4.2.2 on 2023-06-15 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("first", "0002_alter_course_teaser_video_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="short_description",
            field=models.TextField(
                blank=True, max_length=255, verbose_name="Краткое описание"
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="assessment",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="first.assessment",
                verbose_name="Оценка",
            ),
        ),
        migrations.AlterField(
            model_name="subtopic",
            name="short_description",
            field=models.TextField(
                blank=True, max_length=255, verbose_name="Краткое описание"
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="short_description",
            field=models.TextField(
                blank=True, max_length=1024, verbose_name="Краткое описание"
            ),
        ),
    ]
