# Generated by Django 4.2.2 on 2023-06-15 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("first", "0003_alter_course_short_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessment",
            name="assessment_name",
            field=models.CharField(
                max_length=255, verbose_name="Название оценившего теста"
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="assessment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="first.assessment",
                verbose_name="оценивающий тест",
            ),
        ),
    ]
